# Generated by Django 5.0.2 on 2025-03-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_additional_details_shipment_pickup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='dimensions',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('air', 'Air Freight'), ('sea', 'Sea Freight'), ('land', 'Land Transport'), ('courier', 'Courier Service')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='shipments.shipment'),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
