# Generated by Django 5.0.2 on 2025-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_shipment_status_alter_shipmentupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(default='Maris Logistics Ltd', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank', 'Bank Transfer'), ('mpesa', 'M-PESA')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.CharField(default='General Cargo', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
