# Generated by Django 5.1.7 on 2025-04-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_additional_details_shipment_pickup_date_and_more'),
        ('shipments', '0005_shipment_carrier_shipment_payment_mode_and_more'),
    ]

    operations = [
    ] 