# Generated by Django 5.1.7 on 2025-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_alter_shipment_carrier_alter_shipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='payment_mode',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('mpesa', 'M-PESA'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20),
        ),
    ]
