# Generated by Django 5.1.7 on 2025-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_alter_shipment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
