# Generated by Django 5.1.7 on 2025-04-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_inventoryitem_movementhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementhistory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='movementhistory',
            name='from_warehouse',
        ),
        migrations.RemoveField(
            model_name='movementhistory',
            name='to_warehouse',
        ),
        migrations.RemoveField(
            model_name='movementhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='MovementHistory',
        ),
    ]
